> Experiments with [analysis](../trapallada/analysis.py)  module

In [1]:
import pathlib

import trapallada.analysis

So that `import`ed Python modules are automatically reloaded when modified

In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# load_results_dir

The directory with the results...

In [3]:
results_dir = pathlib.Path.cwd().parent / 'samples' / 'results'
assert results_dir.exists()

...contains a bunch of files

In [4]:
list(results_dir.glob('*'))

[PosixPath('/home/manu/Sync/git/trapallada/samples/results/extended_parameters.yaml'),
 PosixPath('/home/manu/Sync/git/trapallada/samples/results/in_training_metrics.parquet'),
 PosixPath('/home/manu/Sync/git/trapallada/samples/results/analysis.parquet'),
 PosixPath('/home/manu/Sync/git/trapallada/samples/results/model.eqx')]

Dataset-related files are also loaded, their path being inferred from the above *paramters* file.

They can all be loaded in one go using

In [5]:
ds, headers_df, model, results_df, parameters, analysis_df = trapallada.analysis.load_results_dir(results_dir, analysis_also=True)

trapallada.data - WARNING - dismissed 929 constant signals (that cannot be normalized); 56323 left

In [6]:
len(ds)

56323

In [7]:
headers_df.head()

                                                        RA        DEC  \
tar file       source
0821871301.tar P0821871301PNS003SRCTSR8001.FTZ  201.089746  31.447543
               P0821871301PNS003SRCTSR8002.FTZ  200.941274  31.658391
               P0821871301PNS003SRCTSR8003.FTZ  200.715039  31.476954
               P0821871301PNS003SRCTSR8004.FTZ  200.936973  31.566037
0904610401.tar P0904610401PNS003SRCTSR8001.FTZ  230.315693   7.508275

                                                       CRA       CDEC
tar file       source
0821871301.tar P0821871301PNS003SRCTSR8001.FTZ  201.090309  31.447292
               P0821871301PNS003SRCTSR8002.FTZ  200.941912  31.658179
               P0821871301PNS003SRCTSR8003.FTZ  200.715612  31.476800
               P0821871301PNS003SRCTSR8004.FTZ  200.937579  31.565825
0904610401.tar P0904610401PNS003SRCTSR8001.FTZ  230.315276   7.508210

In [8]:
model

VAE(
  encoder=Encoder(
    layers=[
      Conv1d(
        num_spatial_dims=1,
        weight=f32[12,1,64],
        bias=f32[12,1],
        in_channels=1,
        out_channels=12,
        kernel_size=(64,),
        stride=(2,),
        padding=((0, 0),),
        dilation=(1,),
        groups=1,
        use_bias=True
      ),
      <wrapped function relu>,
      LayerNorm(
        shape=(12, 81),
        eps=1e-05,
        use_weight=True,
        use_bias=True,
        weight=f32[12,81],
        bias=f32[12,81]
      ),
      Conv1d(
        num_spatial_dims=1,
        weight=f32[12,12,32],
        bias=f32[12,1],
        in_channels=12,
        out_channels=12,
        kernel_size=(32,),
        stride=(2,),
        padding=((0, 0),),
        dilation=(1,),
        groups=1,
        use_bias=True
      ),
      <wrapped function relu>,
      LayerNorm(
        shape=(12, 25),
        eps=1e-05,
        use_weight=True,
        use_bias=True,
        weight=f32[12,25],
        bias=f32[12,25]
      ),
      Conv1d(
        num_spatial_dims=1,
        weight=f32[12,12,16],
        bias=f32[12,1],
        in_channels=12,
        out_channels=12,
        kernel_size=(16,),
        stride=(2,),
        padding=((0, 0),),
        dilation=(1,),
        groups=1,
        use_bias=True
      ),
      <wrapped function relu>,
      LayerNorm(
        shape=(12, 5),
        eps=1e-05,
        use_weight=True,
        use_bias=True,
        weight=f32[12,5],
        bias=f32[12,5]
      ),
      <wrapped function ravel>,
      Linear(
        weight=f32[100,60],
        bias=f32[100],
        in_features=60,
        out_features=100,
        use_bias=True
      ),
      <function <lambda>>
    ],
    layers_spatial_sizes=[225, 81, 25, 5, 60]
  ),
  decoder=Decoder(
    layers=[
      Linear(
        weight=f32[60,50],
        bias=f32[60],
        in_features=50,
        out_features=60,
        use_bias=True
      ),
      <wrapped function relu>,
      <function <lambda>>,
      ConvTranspose1d(
        num_spatial_dims=1,
        weight=f32[12,12,16],
        bias=f32[12,1],
        in_channels=12,
        out_channels=12,
        kernel_size=(16,),
        stride=(2,),
        padding=((0, 0),),
        output_padding=(1,),
        dilation=(1,),
        groups=1,
        use_bias=True
      ),
      <wrapped function relu>,
      LayerNorm(
        shape=(12, 25),
        eps=1e-05,
        use_weight=True,
        use_bias=True,
        weight=f32[12,25],
        bias=f32[12,25]
      ),
      ConvTranspose1d(
        num_spatial_dims=1,
        weight=f32[12,12,32],
        bias=f32[12,1],
        in_channels=12,
        out_channels=12,
        kernel_size=(32,),
        stride=(2,),
        padding=((0, 0),),
        output_padding=(1,),
        dilation=(1,),
        groups=1,
        use_bias=True
      ),
      <wrapped function relu>,
      LayerNorm(
        shape=(12, 81),
        eps=1e-05,
        use_weight=True,
        use_bias=True,
        weight=f32[12,81],
        bias=f32[12,81]
      ),
      ConvTranspose1d(
        num_spatial_dims=1,
        weight=f32[1,12,64],
        bias=f32[1,1],
        in_channels=12,
        out_channels=1,
        kernel_size=(64,),
        stride=(2,),
        padding=((0, 0),),
        output_padding=(1,),
        dilation=(1,),
        groups=1,
        use_bias=True
      )
    ]
  )
)

In [9]:
results_df.head()

      training                            validation
          loss loglikelihood         kl         loss loglikelihood         kl
0  1604.574581  -1582.439688  22.134892  1514.264104  -1474.901742  39.362363
1  1464.669560  -1418.704957  45.964603  1435.541542  -1386.659987  48.881554
2  1415.905453  -1363.628986  52.276464  1396.268006  -1339.756926  56.511080
3  1388.693439  -1333.030668  55.662772  1378.163812  -1321.568050  56.595764
4  1368.972989  -1309.589910  59.383079  1355.724406  -1292.329036  63.395370

In [10]:
analysis_df.head()

,start,end,tar file,source,z_1,z_2,z_3,z_4,z_5,z_6,...,set,cluster in z,cluster in projected space,RA,DEC,CRA,CDEC,main_type,other_types,main_id
0,2018-06-08 20:14:41.569583,2018-06-09 01:58:05.089583,0821871301.tar,P0821871301PNS003SRCTSR8001.FTZ,-1.887069,-1.590130,-1.319296,0.748454,0.480205,-0.228178,...,training,-1,1,201.089746,31.447543,201.090309,31.447292,QSO,*|Opt|QSO|Rad,SDSS J132421.64+312650.8
1,2018-06-08 20:14:41.569583,2018-06-09 01:58:05.089583,0821871301.tar,P0821871301PNS003SRCTSR8002.FTZ,-0.351825,1.584178,1.348995,-0.679100,-0.230440,-0.445272,...,training,-1,1,200.941274,31.658391,200.941912,31.658179,QSO,Opt|QSO,SDSS J132346.07+313929.7
2,2018-06-08 20:14:41.569583,2018-06-09 01:58:05.089583,0821871301.tar,P0821871301PNS003SRCTSR8003.FTZ,0.164086,1.217543,-1.599476,0.073207,0.065743,0.180115,...,training,-1,1,200.715039,31.476954,200.715612,31.476800,QSO,Opt|QSO,SDSS J132251.74+312836.6
3,2018-06-08 20:14:41.569583,2018-06-09 01:58:05.089583,0821871301.tar,P0821871301PNS003SRCTSR8004.FTZ,0.440522,0.100277,-1.385539,-0.235897,-0.426546,-0.866567,...,training,-1,1,200.936973,31.566037,200.937579,31.565825,LINER,*|AG?|G|GiC|GiG|LIN|Opt|Rad|X|rG,NGC 5127
4,2018-06-08 20:30:01.369583,2018-06-09 02:13:24.889583,0821871301.tar,P0821871301PNS003SRCTSR8001.FTZ,1.127789,-0.079465,-1.486683,-1.324232,0.195358,1.171294,...,validation,-1,1,201.089746,31.447543,201.090309,31.447292,QSO,*|Opt|QSO|Rad,SDSS J132421.64+312650.8

# predict_and_plot

The 2nd element in the `Dataset` is encoded in the latent space, a prediction is made, and the latter compared against the real thing.

In [11]:
trapallada.analysis.predict_and_plot(model, ds, 2)

start            2018-06-08 20:14:41.569583
end              2018-06-09 01:58:05.089583
tar file                     0821871301.tar
source      P0821871301PNS003SRCTSR8003.FTZ
Name: 2, dtype: object

alt.Chart(...)