In [89]:
import pathlib
import re
# import argparse

# import yaml
# import pandas as pd
import numpy as np
import scipy
from sklearn.model_selection import train_test_split
import pandas as pd

import jax
import jax.numpy as jnp
import jax.random as jr
import optax
import equinox as eqx
from jaxtyping import Array, Float, Int, PyTree

# from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import Dataset, DataLoader, Subset

import altair as alt

import trapallada.data

In [2]:
# input_directory = pathlib.Path.cwd().parent / "light curves" / "Simulations"
input_directory = pathlib.Path.cwd().parent / "light curves"
assert input_directory.exists()

In [3]:
base_filename = 'small'

signals_file = input_directory / f'{base_filename}_signals.pt'
assert signals_file.exists()

metadata_file = input_directory / f'{base_filename}_labels.parquet'
assert metadata_file.exists

In [4]:
ds = trapallada.data.SignalsDataset(signals_file, metadata_file)
len(ds)

18000

In [5]:
# re_label = re.compile(r'.*_s(\d+)_(\d+)\.mat')
# re_label.match('AM_s1_284.mat').groups()

In [6]:
i = ds.metadata_df[ds.metadata_df['label'] == 'AM'].index[0]
ds.metadata_df.loc[i]

label                    AM
std                     2.0
file name    AM/AM_s2_3.jpg
Name: 12000, dtype: object

In [7]:
# am_files = (input_directory / 'AM').rglob('*.mat')
# y = scipy.io.loadmat(next(iter(am_files)))['y']
# y = scipy.io.loadmat(input_directory / 'Simulations' / 'AM' /  'AM_s2_3.mat')['y']
y = ds[i][1]
df = pd.DataFrame(y.squeeze(), columns=['signal'])
df

       signal
0    2.167470
1    2.730022
2    2.250210
3    2.036631
4    2.202767
..        ...
495  2.698509
496  3.435666
497  4.214709
498  2.854706
499  3.599944

[500 rows x 1 columns]

In [8]:
alt.Chart(df.reset_index()).mark_line().encode(
    x='index', y='signal'
)

alt.Chart(...)

In [9]:
# def read_directory(dir: str | pathlib.Path):
    
#     ys = []
#     cols = []
    
#     # for every file in the directory
#     for f in dir.rglob('*.mat'):
        
#         ys.append(scipy.io.loadmat(f)['y'])

#         sigma, id = re_label.match(f.name).groups()

#         cols.append(f's{sigma}_{id}')
    
#     return pd.DataFrame(np.vstack(ys).T, columns=cols)

In [10]:
# df = read_directory(input_directory / 'AM')
# df.head

In [11]:
# ds[:3][1].squeeze().shape

In [165]:
rng_key = jr.PRNGKey(42)

parameters = {
    'training': {
        'splitting': {
            'test_size':  0.2,
            'random_state': 42
        },
        'batch_size': 32,
        'learning_rate': 1e-3,
    },
}

In [13]:
train_idx, validation_idx = train_test_split(
    np.arange(len(ds)), 
    **parameters['training']['splitting'], 
    shuffle=True,
    stratify=ds.labels
)
train_ds, validation_ds = Subset(ds, train_idx), Subset(ds, validation_idx)

# a random key...
key, subkey = jr.split(rng_key)

# ...to compute a seed for a PyTorch `Generator`...
torch_seed = jr.bits(subkey, (1,), dtype=jnp.uint32).item()
torch_rng = torch.Generator().manual_seed(torch_seed)

# ...meant for "batching" in the `DataLoader`'s
train_dl = DataLoader(train_ds, parameters['training']['batch_size'], shuffle=True, generator=torch_rng)
validation_dl = DataLoader(validation_ds, batch_size=parameters['training']['batch_size'], shuffle=False, generator=torch_rng)

In [14]:
ds.metadata_df.head()

      label  std                file name
0  Constant  1.0  Constant/cLC_s1_793.jpg
1  Constant  3.0  Constant/cLC_s3_524.jpg
2  Constant  3.0  Constant/cLC_s3_956.jpg
3  Constant  3.0  Constant/cLC_s3_283.jpg
4  Constant  5.0  Constant/cLC_s5_666.jpg

The indexes (1st element in the `tuple` for a batch) are used to build a `DataFrame`

In [65]:
batch = next(iter(train_dl))
batch_metadata_df = ds.metadata_df.loc[batch[0]]
# df = pd.DataFrame(batch[1].squeeze().T, columns=batch_metadata_df['label'].astype(str) + '_' + batch_metadata_df['std'].astype(int).astype(str))
df = pd.DataFrame(batch[1].squeeze().T, columns=batch_metadata_df['file name'].str.extract(r'.*/(.*).jpg')[0])
df

,AM_s2_906,FM_s5_307,FM_s4_740,AM_s5_238,cLC_s5_586,cLC_s5_248,FM_s1_465,cLC_s10_135,AM_s5_248,cLC_s3_507,...,cLC_s3_312,cLC_s10_232,AM_s4_999,cLC_s10_645,FM_s1_634,cLC_s1_624,FM_s10_295,FM_s2_497,AM_s4_499,cLC_s3_488
0,9.974388,6.440574,21.569034,41.647796,0.682139,-10.402873,48.295051,-4.344237,12.962303,-0.719106,...,2.396088,5.263309,26.227355,14.428149,32.247807,-0.266728,-0.333451,45.865302,27.144221,1.804945
1,7.854935,2.286819,15.458958,26.643542,1.765054,3.449168,36.394702,1.364026,1.409253,2.674147,...,3.301413,2.958244,19.423850,2.024228,-26.569551,-1.139272,4.516658,42.684193,15.984727,2.154495
2,7.401620,-7.160564,2.847059,26.225561,7.610417,10.902963,5.701338,0.137194,-7.231247,1.284064,...,-0.662248,8.021483,13.711669,3.391752,3.818997,0.336572,6.947814,37.804741,-21.525929,4.619043
3,3.232806,-10.552812,-12.458677,13.875726,-3.478585,6.956614,-28.808371,6.937356,-7.569361,2.933081,...,-2.810892,-13.968496,-3.436231,11.718859,26.971862,2.015155,-1.964616,30.685803,-19.964228,3.498551
4,8.362470,-3.610619,-19.208595,10.778331,8.769910,4.765773,-47.111876,-4.254733,-8.804109,10.556660,...,-3.462929,15.194070,-16.842417,-22.602688,-21.434424,2.133179,-7.194952,23.829883,-11.151784,5.641507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1.733834,-5.377999,14.896126,-9.299699,11.358340,13.129894,-47.707096,43.277120,-6.016494,2.383902,...,19.312984,-19.193088,-4.117230,10.271917,-20.711352,-1.107174,-6.563976,-45.340312,21.346799,-30.218504
496,2.435327,5.475090,21.096056,-17.252791,18.327328,12.996798,-46.278853,38.013375,11.763200,-0.998850,...,15.808646,-43.097418,2.689663,-38.174628,-21.384850,-0.643997,6.519577,-44.854401,1.811497,-30.090864
497,1.508797,3.800788,11.286786,-23.122552,13.593749,11.909723,-43.464088,33.140822,-19.459222,3.659185,...,16.339490,-30.585516,-0.418671,-7.843843,20.279172,0.287928,13.572465,-43.422261,-17.726189,-30.450324
498,2.683124,5.214490,-1.875918,-30.716621,17.815532,-4.181668,-43.504098,62.137035,-7.788140,6.168490,...,14.030261,-10.636155,3.328387,-13.287250,33.089044,-0.394951,7.401115,-44.693165,-14.188805,-30.210021
499,-2.602350,5.904523,-7.472839,-28.252109,20.420414,-9.923847,-37.300487,47.497173,11.719143,7.022504,...,6.641275,-18.421625,10.063190,-17.401630,33.582968,1.006408,1.358748,-45.644271,1.163963,-22.605212

In [68]:
# df = df.iloc[:, :2]
alt.Chart(
    df.reset_index()
).transform_fold(
    df.columns.to_list()
).mark_line().encode(
    x='index:Q', y='value:Q', color='key:N'
).properties(width=1_200, height=400)

alt.Chart(...)

In [69]:
# df_sample = df.sample(n=50, axis=1)
# alt.Chart(
#     df_sample.reset_index()
# ).transform_fold(
#     df_sample.columns.to_list()
# ).mark_line().encode(
#     x='index:Q', y='value:Q', color='key:N'
# ).properties(width=1_200, height=400)

In [195]:
x = df.iloc[:, 0:1].values.T
in_channels = 1
x.shape

(1, 500)

In [196]:
stride = 4

In [197]:
out_channels = 2
conv = eqx.nn.Conv1d(in_channels=in_channels, out_channels=out_channels, kernel_size=60, stride=stride, key=jr.PRNGKey(42))
in_channels = out_channels
pool = eqx.nn.MaxPool1d(kernel_size=2)
# x = conv(x)
x = jax.nn.relu(pool(conv(x)))
x.shape

(2, 110)

In [199]:
out_channels = 4
conv = eqx.nn.Conv1d(in_channels=in_channels, out_channels=out_channels, kernel_size=25, stride=stride, key=jr.PRNGKey(42))
in_channels = out_channels
x = jax.nn.relu(pool(conv(x)))
x.shape

(4, 21)

In [200]:
out_channels = 8
conv = eqx.nn.Conv1d(in_channels=in_channels, out_channels=out_channels, kernel_size=10, stride=stride, key=jr.PRNGKey(42))
in_channels = out_channels
x = jax.nn.relu(pool(conv(x)))
x.shape

(8, 2)

In [202]:
x = jnp.ravel(x)
x.shape

In [208]:
linear = eqx.nn.Linear(in_features=np.prod(x.shape), out_features=3, key=jr.PRNGKey(42))
linear(x)

Array([-0.99535525, -0.08502249,  0.19692653], dtype=float32)

In [130]:
jr.split(jr.PRNGKey(42))

Array([[2465931498, 3679230171],
       [ 255383827,  267815257]], dtype=uint32)

In [131]:
class Classifier(eqx.Module):

    layers: list

    def __init__(self, rng_key):

        # key1, key2, key3, key4, key5, key6, key7, key8 = jr.split(rng_key, 8)

        stride = 4

        # self.layers = [
        #     eqx.nn.Conv1d(in_channels=1, out_channels=2, kernel_size=60, stride=stride, key=key1),
        #     eqx.nn.MaxPool1d(kernel_size=2),
        #     jax.nn.relu,
        #     #
        #     eqx.nn.Conv1d(in_channels=2, out_channels=4, kernel_size=25, stride=stride, key=key2),
        #     eqx.nn.MaxPool1d(kernel_size=2),
        #     jax.nn.relu,
        #     #
        #     eqx.nn.Conv1d(in_channels=4, out_channels=8, kernel_size=10, stride=stride, key=key3),
        #     eqx.nn.MaxPool1d(kernel_size=2),
        #     jax.nn.relu,
        # ]

        self.layers = []

        channels = [1, 2, 4, 8]
        kernel_sizes = [50, 30, 15]

        for in_channels, out_channels, key, kernel_size in zip(
            channels[:-1], channels[1:],
            jr.split(jr.PRNGKey(42), len(channels) - 1),
            kernel_sizes
        ):
            
            self.layers.extend([
                eqx.nn.Conv1d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, key=key),
                eqx.nn.MaxPool1d(kernel_size=2),
                jax.nn.relu,
            ])

        self.layers.append(jnp.squeeze)

        key, subkey = jr.split(key)
        self.layers.append(eqx.nn.Linear(in_features=channels[-1], out_features=3, key=subkey))
        
    def __call__(self, x: Float[Array, '1 length'] ) -> Float[Array, 'twice_dim_z']:

        for layer in self.layers:

            x = layer(x)

        return x

    def debug_call(self, x: Float[Array, '1 length'] ) -> Float[Array, 'twice_dim_z']:

        for layer in self.layers:

            x = layer(x)
            print(f'after {layer.__module__}: {x.shape}')

# x = df.iloc[:, 0:1].values.T
x = batch[1][0].numpy()
model = Classifier(jr.PRNGKey(42))
model.debug_call(x)

after equinox.nn._conv: (2, 113)
after equinox.nn._pool: (2, 112)
after jax._src.nn.functions: (2, 112)
after equinox.nn._conv: (4, 21)
after equinox.nn._pool: (4, 20)
after jax._src.nn.functions: (4, 20)
after equinox.nn._conv: (8, 2)
after equinox.nn._pool: (8, 1)
after jax._src.nn.functions: (8, 1)
after jax._src.numpy.lax_numpy: (8,)
after equinox.nn._linear: (3,)

In [132]:
# print(model)

In [135]:
y_pred = jax.vmap(model)(batch[1].numpy())
y_pred.shape

(32, 3)

In [109]:
def cross_entropy(
    y: Int[Array, " batch"], pred_y: Float[Array, "batch 3"]
) -> Float[Array, ""]:
    # y are the true targets, and should be integers 0-9.
    # pred_y are the log-softmax'd predictions.
    pred_y = jnp.take_along_axis(pred_y, jnp.expand_dims(y, 1), axis=1)
    return -jnp.mean(pred_y)

In [121]:
y = jnp.array([1, 2, 3])
y_pred = jnp.array([
    [0.1, 0.6, 0.1, 0.2],
    [0.1, 0.1, 0.6, 0.2],
    [0.1, 0.1, 0.1, 0.7]
])
print(y, '\n', y_pred)

[1 2 3]
 [[0.1 0.6 0.1 0.2]
 [0.1 0.1 0.6 0.2]
 [0.1 0.1 0.1 0.7]]

In [122]:
cross_entropy(y, y_pred)

Array(-0.6333333, dtype=float32)

In [117]:
# optax.losses.softmax_cross_entropy_with_integer_labels(y_pred, y).mean()

Array(1.7928747, dtype=float32)

In [136]:
def loss(model: eqx.Module, x: Float[Array, 'batch length'], y: Float[Array, 'batch']):

    y_pred = jax.vmap(model)(x)
    
    return optax.losses.softmax_cross_entropy_with_integer_labels(y_pred, y).mean()

In [137]:

loss(model, batch[1].numpy(), batch[2].numpy())

Array(1.1721073, dtype=float32)

In [166]:
optim = optax.adamw(parameters['training']['learning_rate'])
opt_state = optim.init(eqx.filter(model, eqx.is_array))

In [141]:
@eqx.filter_jit
def take_step(
    model,
    opt_state: PyTree,
    x: Float[Array, 'batch 1 length'],
    y: Float[Array, 'batch']
) -> tuple[tuple[eqx.Module], PyTree, Float[Array, '']]:

    value, grads = eqx.filter_value_and_grad(loss)(model, x, y)

    # it returns transformed/processed gradients, and the optimizer state
    updates, opt_state = optim.update(grads, opt_state, model)

    model = eqx.apply_updates(model, updates)

    return model, opt_state, value

In [152]:
# model, opt_state, value = take_step(model, opt_state, batch[1].numpy(), batch[2].numpy())
# value

Array(0.76158667, dtype=float32)

In [167]:
n_epochs = 200

train_loss = [None] * n_epochs
valid_loss = [None] * n_epochs

In [168]:
for epoch in range(n_epochs):

    train_loss[epoch] = 0.

    for _, x, y in train_dl:

        key, subkey = jr.split(key)

        model, opt_state, loss_value = take_step(model, opt_state, x.numpy(), y.numpy())

        train_loss[epoch] += loss_value.item()

    # validation
    valid_loss[epoch] = 0.
    
    for _, x, y in validation_dl:
    
        loss_value = loss(model, x.numpy(), y.numpy())
        
        valid_loss[epoch] += valid_loss.item()

    valid_loss[epoch] /= len(validation_dl)

    print(epoch, train_loss[epoch] / len(train_dl), valid_loss[epoch])

0 0.38656039641963114 0.41880728647244714
1 0.3803364422917366 0.4145087538435396
2 0.3791669511795044 0.4044460246784497
3 0.3771887627575133 0.41343845110551447
4 0.37197291526529525 0.40502711945930414
5 0.3746709357202053 0.3991425831892849
6 0.3779253030485577 0.3998234130903683
7 0.3713621832099226 0.4062693202126343
8 0.3662505098846224 0.41132528394196943
9 0.3723984309534232 0.42008405317247444
10 0.37209910253683726 0.4033900753191087
11 0.362975840833452 0.4127994781706186
12 0.3683379554086261 0.41393773745646517
13 0.3695166864991188 0.4039837892735954
14 0.36087198904818957 0.41711982906655926
15 0.3677493368089199 0.41016503561914497
16 0.35672791906529 0.42945289690937616
17 0.3623781364162763 0.41393214009240664
18 0.3675827976895703 0.44836000814638305
19 0.35685801287492114 0.39605212666555845
20 0.36053584572341707 0.4142340850249856
21 0.3571645718316237 0.4089219139608662
22 0.35689616761273807 0.44662129694381647
23 0.3535249304274718 0.4076439912340282
24 0.3619463975065284 0.4011069610055569
25 0.35428862545225354 0.41785389831108327
26 0.35078801572322843 0.4401417464940949
27 0.35424227189686563 0.41367668843111105
28 0.34952787443995476 0.41229347911028735
29 0.35970248618059686 0.41069792151714846
30 0.3591529608600669 0.4010262544044351
31 0.3474275926252206 0.41765897833140553
32 0.3510960469312138 0.40438540866680905
33 0.34667453457911807 0.4277540910164867
34 0.3525534936951266 0.40629801787106334
35 0.35329623982310293 0.40552066846758916
36 0.3493913502494494 0.4252815871639589
37 0.35125946222080123 0.4168542916927717
38 0.3451804487241639 0.39821752516833026
39 0.3485109717150529 0.4047672999116172
40 0.34263047438528804 0.395158567259797
41 0.3505302730533812 0.4031032059440571
42 0.3422010516458088 0.4115446504634038
43 0.3459904370539718 0.41320339834268116
44 0.3500696373482545 0.4167620130212961
45 0.34265495479106906 0.41063892445733063
46 0.3496243109471268 0.41778926518374837
47 0.34073413320713575 0.40360592378188026
48 0.337721024884118 0.421310698234402
49 0.34647232109473813 0.40324813167078305
50 0.343665921025806 0.4057055634603036
51 0.3462586592965656 0.4206154244927178
52 0.33617212216059367 0.43471336114195597
53 0.346134325630135 0.40087299998355125
54 0.3403108034862412 0.4148951596127147
55 0.3369924753573206 0.41578324000656075
56 0.3361001514891783 0.39573305812293447
57 0.34056629644499886 0.4105702879945789
58 0.33974289170569844 0.41189516830233347
59 0.33673574783735805 0.41445639584444266
60 0.3394740812977155 0.4141180134848156
61 0.33682170497046576 0.4018154756157799
62 0.3393891981906361 0.4090358174480168
63 0.33924170061945913 0.4196693293948089
64 0.33967091442810166 0.4114717478509498
65 0.33231804344389176 0.414975450893419
66 0.3381042754318979 0.41500230067599136
67 0.33436258167028426 0.4179097622369243
68 0.3340591882500384 0.4087253611172195
69 0.3370617116987705 0.4104870166135045
70 0.33078366181916663 0.39923961882570147
71 0.3399966624379158 0.4030241088002129
72 0.3392756690416071 0.41959639869432536
73 0.3303363687958982 0.4175383844866162
74 0.33602854788303377 0.42142195491927914
75 0.33408157537380856 0.4182353259715359
76 0.3355654836528831 0.4038917033282001
77 0.33702844608161187 0.4210747648525027
78 0.32941426270537905 0.4243334779697182
79 0.3296079094873534 0.4280916532847734
80 0.3357742763062318 0.4301479928261411
81 0.33326684412029056 0.40898873821824
82 0.3268726944592264 0.42740348126508493
83 0.33625399102767306 0.40489388804520127
84 0.3308508280581898 0.4099086027229782
85 0.33523012523849804 0.4179811923377282
86 0.33356950531403223 0.4337282248039161
87 0.33130700437559024 0.41456546047620013
88 0.32682718094852237 0.41628206864131234
89 0.33746436047885153 0.41726749317835915
90 0.33263629111978743 0.4284518619554233
91 0.33274921559625203 0.413007551721767
92 0.3288965482181973 0.4076596936293408
93 0.3309612865580453 0.40995809343536344
94 0.3352451894018385 0.40976198189026486
95 0.3345648421016004 0.41245917619857114
96 0.32585971848832235 0.41700512869695644
97 0.3240702277421951 0.4243873297113233
98 0.3334747363626957 0.42704757111789904
99 0.3330586497982343 0.41005370515373957
100 0.32828450390034253 0.41757490241949535
101 0.32540742380751503 0.4065244791913876
102 0.3265139602786965 0.43357666074174694
103 0.3340772983431816 0.41573194526465596
104 0.3309210871656736 0.40859061512535655
105 0.3247207792268859 0.4144060384251375
106 0.3223509915669759 0.4000978306331466
107 0.3338537342556649 0.41391492681165715
108 0.3291579458117485 0.41080978314960953
109 0.3297214689685239 0.40981593780812964
110 0.3266003208524651 0.4121819968640277
111 0.32375991496774886 0.4087537367523244
112 0.3256441903942161 0.4197167180544507
113 0.3251440288623174 0.405349155904445
114 0.32812762048509386 0.42771339205514014
115 0.32759845450520514 0.4226413503684829
116 0.3285467969708972 0.44052478895250674
117 0.32188642974529 0.4212459538098985
118 0.3214851791659991 0.41585821915516813
119 0.33170191892319256 0.4214235239588054
120 0.3304175442126062 0.4154970132935364
121 0.3211403791937563 0.42682750417595416
122 0.32412004007233514 0.41577809244658037
123 0.32492847247256174 0.42586950522608463
124 0.32211896577643023 0.44190304548339504
125 0.3246136000255744 0.42356613667401594
126 0.32305054331819216 0.4194778631218767
127 0.3271000298195415 0.4245466640037773
128 0.3225050495399369 0.4216617638558413
129 0.3352866560882992 0.41393483027947686
130 0.32534406398733456 0.41797089233862617
131 0.319907009386354 0.4184844078479615
132 0.32260544238819017 0.41250263741322324
133 0.3172600274615818 0.41324256967126793
134 0.32682163710395495 0.4423608972435504
135 0.3276634356876214 0.4371439463796869
136 0.328224129445023 0.4313178067054369
137 0.3194809809492694 0.4140717785442825
138 0.32810761359002855 0.42574781957453334
139 0.3207286249101162 0.41534348109127145
140 0.32377228748467235 0.4373308668094399
141 0.3220888389647007 0.4295069268055722
142 0.3217393591172165 0.4867110207545019
143 0.3287450794544485 0.44746734030478824
144 0.3255453458262814 0.4186634352776857
145 0.32037959271007116 0.4409410801872743
146 0.3300260472214884 0.42516059079001434
147 0.3203349067270756 0.4031366245672766
148 0.3200669263799985 0.4256979970805413
149 0.3199669819863306 0.42605981402165066
150 0.32684135844310125 0.4324848671666289
151 0.32567510563466284 0.4934402925778279
152 0.3248219070997503 0.4198633272827199
153 0.3211501246525182 0.4149946706221167
154 0.3254842401213116 0.4115847126968139
155 0.3157407083776262 0.4340399894039188
156 0.3228041043215328 0.42088255299403604
157 0.3229080965618292 0.40517295910193857
158 0.3224224460290538 0.4121674826714845
159 0.31861174588402114 0.4172870318974014
160 0.32157560194532075 0.42522060079912166
161 0.3227324650188287 0.41950487787217167
162 0.31538462383879556 0.414909888289671
163 0.3176226057940059 0.4158866340871406
164 0.333071608112918 0.43038407376909676
165 0.3245768893427319 0.4183170045107867
166 0.32014245897531507 0.4272542188389111
167 0.3286267142660088 0.4264793934020321
168 0.32245699226856234 0.40958042957086477
169 0.318768823908435 0.42495460755529657
170 0.3210432529449463 0.4175191039005212
171 0.31702977235118546 0.4341933040228565
172 0.3182629043194983 0.4267337910369434
173 0.3304962170124054 0.41709111934214566
174 0.3187838036153052 0.4031519988073712
175 0.31630088112420507 0.4273364566332471
176 0.3206451110293468 0.42591561218806073
177 0.3198270494076941 0.4134163860462408
178 0.3217845288084613 0.4455865711237477
179 0.31540728041695226 0.42827655315662905
180 0.32033155295583937 0.42746032411809515
181 0.31730053959621324 0.4253579313512397
182 0.32043834808799954 0.4311129528600558
183 0.3224182705084483 0.45381054677794463
184 0.32242150554226506 0.42994271825372643
185 0.3190100196666188 0.4160231299764287
186 0.3215019649432765 0.4307065304137964
187 0.3141671377999915 0.4354079832545424
188 0.31229859991206066 0.4301515403574547
189 0.32552233952614995 0.4365496627524891
190 0.3151100751426485 0.42777048222786557
191 0.31452712135182487 0.4248355677170036
192 0.32041896830002464 0.4410165390082165
193 0.31513631876971987 0.42389529350057115
194 0.3179835336820947 0.42089082129233707
195 0.32029610152045884 0.4189620294929606
196 0.3183109004795551 0.4197238849855102
197 0.3151605708897114 0.42830768247357515
198 0.3192390693061882 0.41674848632738654
199 0.32524900984432964 0.45501967882160593