> Download and tidy up *real* data for training.

In [1]:
import pathlib
import os

import torch

import trapallada.xsa.access
import trapallada.xsa.util
import trapallada.data
import trapallada.plot

So that the notebook is aware of modifications in the the `import`ed modules

In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

The directory where observations' data will be saved

In [3]:
download_directory =  pathlib.Path(os.environ['MY_DATA_DIR']) / 'trapallada'
download_directory.mkdir(exist_ok=True)

That in which data will be saved

In [4]:
output_directory = pathlib.Path.cwd().parent / 'data'
assert output_directory.exists()

## Data for Javi's paper

In [5]:
javi_obs = '0605950101'
javi_obs_dir = trapallada.xsa.util.download_extract_filter(obs=javi_obs, output_directory=download_directory)
javi_obs_dir

trapallada.xsa.util - INFO - found file "/home/manu/data/trapallada/0605950101.tar", extracting...

found directory "/home/manu/data/trapallada/0605950101", skipping...

PosixPath('/home/manu/data/trapallada/0605950101')

The downloaded files

In [6]:
fits_files = list(javi_obs_dir.glob('*.FTZ'))
fits_files[:3]

[PosixPath('/home/manu/data/trapallada/0605950101/P0605950101PNS003SRCTSR802C.FTZ'),
 PosixPath('/home/manu/data/trapallada/0605950101/P0605950101PNS003SRCTSR8016.FTZ'),
 PosixPath('/home/manu/data/trapallada/0605950101/P0605950101PNS003SRCTSR801F.FTZ')]

In [7]:
df, skipped_files_list = trapallada.xsa.util.read_fits_files(fits_files)
print(f'len{skipped_files_list=}')
df.head()

lenskipped_files_list=[]

,P0605950101PNS003SRCTSR802C.FTZ,P0605950101PNS003SRCTSR8016.FTZ,P0605950101PNS003SRCTSR801F.FTZ,P0605950101PNS003SRCTSR8020.FTZ,P0605950101PNS003SRCTSR800F.FTZ,P0605950101PNS003SRCTSR802B.FTZ,P0605950101PNS003SRCTSR804C.FTZ,P0605950101PNS003SRCTSR8008.FTZ,P0605950101PNS003SRCTSR8018.FTZ,P0605950101PNS003SRCTSR8022.FTZ,...,P0605950101PNS003SRCTSR8064.FTZ,P0605950101PNS003SRCTSR8036.FTZ,P0605950101PNS003SRCTSR8030.FTZ,P0605950101PNS003SRCTSR8012.FTZ,P0605950101PNS003SRCTSR8021.FTZ,P0605950101PNS003SRCTSR801C.FTZ,P0605950101PNS003SRCTSR801A.FTZ,P0605950101PNS003SRCTSR8009.FTZ,P0605950101PNS003SRCTSR8002.FTZ,P0605950101PNS003SRCTSR8032.FTZ
TIME,,,,,,,,,,,,,,,,,,,,,
2009-06-03 08:10:33.517454,0.000000,0.0,-0.030024,0.0,0.000000,0.000000,0.0,0.837148,0.000000,0.0,...,0.00000,0.0,-0.02643,0.000000,0.0,0.0,-0.00934,-0.125560,0.808501,0.000000
2009-06-03 08:10:34.977454,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,-0.03712,0.0,0.00000,0.000000,0.0,0.0,0.00000,0.000000,0.771650,0.000000
2009-06-03 08:10:36.437454,0.000000,0.0,0.000000,0.0,-0.050389,-0.020843,0.0,0.000000,0.000000,0.0,...,0.00000,0.0,0.00000,0.000000,0.0,0.0,0.00000,0.000000,0.765734,0.000000
2009-06-03 08:10:37.897454,-0.010277,0.0,0.000000,0.0,0.000000,0.000000,0.0,-0.090626,-0.010292,0.0,...,0.00000,0.0,0.00000,0.000000,0.0,0.0,0.00000,0.778995,0.000000,0.000000
2009-06-03 08:10:39.357454,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,0.00000,0.0,0.00000,-0.104794,0.0,0.0,0.00000,0.000000,0.778009,-0.021274

We have `number of rows` measurements for each one of the `number of columns` signals

In [8]:
df.shape

(31805, 49)

The period is

In [9]:
df.index[1] - df.index[0]

Timedelta('0 days 00:00:01.460000')

Signals are *binned* so that a bunch of samples/measurements are added up together

In [10]:
bin_size = 63
# bin_size = 5
binned_df = trapallada.xsa.util.bin_fits_df(df, bin_size=bin_size)
binned_df

,P0605950101PNS003SRCTSR802C.FTZ,P0605950101PNS003SRCTSR8016.FTZ,P0605950101PNS003SRCTSR801F.FTZ,P0605950101PNS003SRCTSR8020.FTZ,P0605950101PNS003SRCTSR800F.FTZ,P0605950101PNS003SRCTSR802B.FTZ,P0605950101PNS003SRCTSR804C.FTZ,P0605950101PNS003SRCTSR8008.FTZ,P0605950101PNS003SRCTSR8018.FTZ,P0605950101PNS003SRCTSR8022.FTZ,...,P0605950101PNS003SRCTSR8064.FTZ,P0605950101PNS003SRCTSR8036.FTZ,P0605950101PNS003SRCTSR8030.FTZ,P0605950101PNS003SRCTSR8012.FTZ,P0605950101PNS003SRCTSR8021.FTZ,P0605950101PNS003SRCTSR801C.FTZ,P0605950101PNS003SRCTSR801A.FTZ,P0605950101PNS003SRCTSR8009.FTZ,P0605950101PNS003SRCTSR8002.FTZ,P0605950101PNS003SRCTSR8032.FTZ
TIME,,,,,,,,,,,,,,,,,,,,,
2009-06-03 08:12:05.497454,0.616343,0.709275,0.736227,-0.069906,-0.632557,-0.309294,-0.228722,5.138829,-0.158042,-0.083375,...,-0.262807,-0.082086,-0.069965,0.696522,-0.098157,-0.094558,-0.069920,3.649674,46.343955,0.698373
2009-06-03 08:13:37.477454,-0.052528,0.853867,-0.132543,0.686867,2.253208,-0.062261,-0.094323,9.597126,1.483293,0.736150,...,-0.037978,0.648857,0.655573,-0.106176,-0.048485,-0.094227,0.698083,1.150647,36.475717,-0.173611
2009-06-03 08:15:09.457454,0.659836,0.703072,-0.252387,1.459107,0.575144,-0.211291,-0.188976,7.259375,-0.094219,-0.165744,...,-0.191542,-0.130212,-0.093956,0.684639,-0.196848,-0.107213,-0.171560,-0.346302,25.931725,0.522789
2009-06-03 08:16:41.437454,1.515753,0.724594,-0.127593,-0.100040,0.359564,-0.175420,0.640891,3.816259,-0.214248,-0.147372,...,2.289060,-0.168128,-0.164621,0.000000,-0.156125,-0.106646,0.877948,-0.829979,39.233786,-0.149306
2009-06-03 08:18:13.417454,-0.082870,2.232283,-0.024802,-0.070155,0.418255,0.483381,-0.343177,3.294879,0.672545,-0.084331,...,-0.226527,-0.117162,-0.094184,-0.106507,0.641304,-0.060782,-0.155570,0.204218,31.612971,-0.172412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-06-03 20:57:03.517454,-0.128486,-0.050157,-0.101599,0.694242,-0.266064,-0.145322,-0.070972,9.849914,-0.169855,0.608703,...,0.000000,0.653262,-0.141611,1.036225,-0.131034,-0.125625,0.668797,1.899525,30.035924,-0.177959
2009-06-03 20:58:35.497454,-0.105536,-0.074993,-0.107993,-0.164689,-0.152255,0.654042,-0.191215,4.066569,-0.137068,-0.089823,...,-0.113557,-0.084125,-0.070006,-0.105928,-0.246524,-0.142055,-0.035045,-0.345283,31.476628,-0.085776
2009-06-03 21:00:07.477454,0.663818,-0.050765,-0.080805,-0.119032,0.349739,-0.223008,-0.147110,5.219425,-0.083108,-0.138369,...,-0.152405,-0.117322,-0.116684,-0.209028,-0.024535,-0.123402,-0.042503,-0.466309,27.180789,-0.234778
2009-06-03 21:01:39.457454,-0.103075,-0.151698,-0.050601,-0.101572,1.095180,0.739339,-0.250560,6.656021,-0.127574,-0.082643,...,0.534053,0.663460,-0.140961,-0.215803,-0.024846,-0.146519,-0.087895,3.685644,35.805049,0.650497
2009-06-03 21:03:11.437454,-0.126198,-0.075892,-0.176029,-0.117881,1.930125,-0.197856,-0.148118,7.390902,-0.158851,-0.230359,...,0.631399,-0.069917,-0.047040,-0.104738,-0.130500,-0.118857,-0.076704,1.551898,29.467678,-0.171291

The period is now

In [11]:
binned_df.index[1] - binned_df.index[0]

Timedelta('0 days 00:01:31.980000')

Signals might have `NaN`s

In [12]:
signals = binned_df.values.T
np.isnan(signals).sum()
# np.argwhere(np.isnan(signals))

49

if there are `NaN`s, they are fixed by interpolation

In [13]:
if binned_df.isna().any().any():
    binned_df = binned_df.interpolate(method='linear', axis=0)

In [14]:
n_samples_to_plot = 2_000
sample_signal = binned_df['P0605950101PNS003SRCTSR8001.FTZ'].iloc[:n_samples_to_plot].values
trapallada.plot.signal(sample_signal)

alt.Chart(...)

Output file...

In [15]:
output_file = (output_directory / f'{javi_obs}_bin_size_{bin_size}').with_suffix('.pt')
output_file

PosixPath('/home/manu/Sync/git/trapallada/data/0605950101_bin_size_63.pt')

...to save the signals (notice we add an extra *dummy* axis)

In [16]:
torch.save(np.expand_dims(binned_df.values.T, 1), output_file)

A `SignalsDataset` is instantiated...

In [17]:
ds = trapallada.data.SignalsDataset(output_file, metadata_filename=None, normalize=True)
len(ds)

49

...and plotted

In [18]:
trapallada.plot.signals_dataset(ds, columns=[pathlib.Path(c).stem for c in df.columns], n_signals=None, n_samples=1_000)

alt.Chart(...)

A particular signal

# Dataset

**All** the observations in XSA whose duration is in the given interval are downloaded

In [19]:
# trapallada.xsa.util.download_observations(download_directory=download_directory, duration_interval=(35_000, 45_000))

The *tar* files in the download directory

In [20]:
tar_files = list(download_directory.glob('*.tar'))
tar_files[:3]

[PosixPath('/home/manu/data/trapallada/0821871301.tar'),
 PosixPath('/home/manu/data/trapallada/0904610401.tar'),
 PosixPath('/home/manu/data/trapallada/0792382701.tar')]

In [21]:
fits_df = trapallada.xsa.util.read_tar(tar_files[2], max_n_sources=4)
fits_df

,P0792382701PNS001SRCTSR8001.FTZ,P0792382701PNS001SRCTSR8002.FTZ,P0792382701PNS001SRCTSR8003.FTZ,P0792382701PNS001SRCTSR8004.FTZ
TIME,,,,
2016-08-23 17:34:59.032027,0.788578,0.000000,0.000000,0.000000
2016-08-23 17:35:00.492027,1.554315,0.000000,-0.040462,0.000000
2016-08-23 17:35:01.952027,0.770937,0.770639,0.000000,0.000000
2016-08-23 17:35:03.412027,0.000000,0.000000,0.000000,0.000000
2016-08-23 17:35:04.872027,0.000000,1.547701,0.000000,-0.047675
...,...,...,...,...
2016-08-24 03:02:14.552027,1.495120,0.403041,0.809779,-0.207217
2016-08-24 03:02:16.012027,2.517750,0.823421,-0.085930,-0.050086
2016-08-24 03:02:17.472027,1.673615,0.384002,0.779530,-0.098520
2016-08-24 03:02:18.932027,0.787459,0.373316,-0.081060,-0.048329
2016-08-24 03:02:20.392027,0.000000,0.000000,0.000000,0.000000

In [22]:
fits_df.index[1] - fits_df.index[0]

Timedelta('0 days 00:00:01.460000')

If there is *any* `NaN` at all (in any column, at any time instant), it's filled in using interpolation.

In [23]:
if fits_df.isna().any().any():
    print('Interpolating...')
    fits_df = fits_df.interpolate(method='linear', axis=0)

Interpolating...

In [24]:
bin_size = 63
# bin_size = 32
binned_df = trapallada.xsa.util.bin_fits_df(fits_df, bin_size=bin_size)
binned_df

,P0792382701PNS001SRCTSR8001.FTZ,P0792382701PNS001SRCTSR8002.FTZ,P0792382701PNS001SRCTSR8003.FTZ,P0792382701PNS001SRCTSR8004.FTZ
TIME,,,,
2016-08-23 17:36:31.012027,95.256013,32.764331,3.366886,1.639905
2016-08-23 17:38:02.992027,84.011466,36.439104,3.272848,0.922849
2016-08-23 17:39:34.972027,104.693468,30.664729,5.234119,0.940626
2016-08-23 17:41:06.952027,102.260127,34.761046,7.273077,5.888420
2016-08-23 17:42:38.932027,94.736061,27.180292,5.550118,1.975234
...,...,...,...,...
2016-08-24 02:56:03.712027,124.632772,0.000000,74.627845,-3.715284
2016-08-24 02:57:35.692027,99.266601,0.000000,72.567963,-4.636791
2016-08-24 02:59:07.672027,107.204760,35.361402,3.720179,-0.273973
2016-08-24 03:00:39.652027,94.800618,39.615359,4.454318,6.871394
2016-08-24 03:02:11.632027,111.692796,29.474087,4.436156,2.838963

In [25]:
period = binned_df.index[1] - binned_df.index[0]
period

Timedelta('0 days 00:01:31.980000')

In [26]:
trapallada.plot.df(binned_df, columns=[pathlib.Path(e).stem for e in binned_df.columns], index_type='T')

alt.Chart(...)

In [28]:
sliced_signals, sliced_times = trapallada.xsa.util.slice(binned_df, window_size=90, step=50, tail_as_window=False)
sliced_signals.shape

(24, 90)

In [29]:
sliced_signals[3]

array([1.6399046 , 0.92284908, 0.94062643, 5.88842034, 1.97523431,
       1.11481909, 3.1717988 , 1.46687232, 1.11797179, 4.23964993,
       1.44313677, 2.59604739, 3.1701548 , 1.49289265, 4.70300619,
       2.62415607, 1.77912118, 5.22181317, 1.65650971, 1.04335969,
       1.29931317, 5.32119   , 1.72557224, 0.78290717, 5.96575294,
       2.24254955, 0.91134372, 1.89784148, 3.42626521, 3.53590561,
       3.36308193, 5.11633063, 3.26458591, 1.89071211, 4.38317183,
       1.79218572, 3.87620549, 5.73043374, 1.23565292, 1.68810755,
       4.16672776, 2.09953348, 3.51627554, 1.59771436, 1.03375579,
       1.08012911, 2.21536511, 4.53490034, 3.22772473, 5.67453898,
       5.7899823 , 2.0124682 , 2.58230323, 2.70491017, 3.87040359,
       1.51910612, 2.34788764, 0.59534446, 5.08861482, 4.13574946,
       1.36160882, 3.92251512, 2.62172302, 2.36203677, 3.33536249,
       2.54712869, 4.09433199, 3.32468729, 2.36847894, 1.79928694,
       4.10932184, 4.08557545, 3.60666591, 1.11267846, 0.25929576,
       6.07952583, 2.54773808, 5.02349366, 3.53117153, 1.73013689,
       3.39394382, 4.01044641, 1.72286151, 5.05003411, 4.23933687,
       0.87395945, 1.90629272, 1.34497959, 2.30559986, 5.20950939])

In [30]:
trapallada.plot.signals_array(sliced_signals)

alt.Chart(...)

In [31]:
signals, metadata_df = trapallada.xsa.util.tars_to_array(tar_files[:5])
# signals, metadata_df = trapallada.xsa.util.tars_to_array(tar_files)

trapallada.xsa.util - INFO - Requested a window size of, effectively, duration 18396.0 seconds (period is 91.98 seconds, step is 4599.0 seconds)

50

In [32]:
metadata_df.head()

,start,end,tar file,source
0,2018-06-08 20:14:41.569583,2018-06-09 01:19:45.589583,0821871301.tar,P0821871301PNS003SRCTSR8001.FTZ
1,2018-06-08 20:14:41.569583,2018-06-09 01:19:45.589583,0821871301.tar,P0821871301PNS003SRCTSR8002.FTZ
2,2018-06-08 20:14:41.569583,2018-06-09 01:19:45.589583,0821871301.tar,P0821871301PNS003SRCTSR8003.FTZ
3,2018-06-08 20:14:41.569583,2018-06-09 01:19:45.589583,0821871301.tar,P0821871301PNS003SRCTSR8004.FTZ
4,2018-06-08 21:31:20.569583,2018-06-09 02:36:24.589583,0821871301.tar,P0821871301PNS003SRCTSR8001.FTZ

The base name for the output files...

In [33]:
output_file_stem = 'sample_35000_45000'

...to be saved

In [34]:
torch.save(torch.from_numpy(np.expand_dims(signals, 1)), (output_directory / (output_file_stem + '_signals')).with_suffix('.pt'))
metadata_df.to_parquet((output_directory / (output_file_stem + '_metadata')).with_suffix('.parquet'))

A *PyTorch* `Dataset` is built

In [35]:
ds = trapallada.data.SignalsDataset(
    (output_directory / (output_file_stem + '_signals')).with_suffix('.pt'),(output_directory / (output_file_stem + '_metadata')).with_suffix('.parquet'), normalize=True)

A particular sample

In [36]:
i = 10
print(ds[i])
trapallada.plot.signal(ds[i][1][0])

(10, tensor([[ 1.2343, -0.3362,  0.1452, -0.5843, -0.2815, -0.8732, -0.4912, -0.7623,
          0.3262,  0.4149,  1.2038, -1.5273,  0.1589, -0.2882,  0.7718, -1.4197,
          0.2667, -0.0997, -1.2497,  0.1346, -1.8551,  0.9659,  1.2896, -0.3347,
          0.0199,  0.3763, -2.0523, -1.3251, -0.7731,  0.2226, -2.0197, -0.2805,
         -0.3414, -1.9103,  0.9588,  0.0963,  1.5382,  1.1747,  1.4888,  0.6646,
         -0.3830,  0.3613, -0.6573,  0.7567, -0.6471, -0.8221, -1.0591, -1.0440,
          0.7737,  0.8809,  1.1285, -0.8880, -1.8062, -0.6479, -0.8228, -0.3387,
          2.6372,  0.0954,  1.1951,  0.2405,  1.1088, -0.7032, -0.8827,  0.6435,
          0.2449, -1.7869, -0.2817, -0.6265,  1.6184, -0.3323, -0.5416, -1.3065,
          0.3305, -0.3766,  1.9965, -0.4466, -1.2083,  0.2036,  1.6943, -1.7900,
          0.2303, -0.2715,  0.7079, -0.2505,  1.4671,  1.7979, -1.1870,  0.9071,
          0.9603,  1.7813, -0.3283, -0.7619,  0.2210, -0.8180, -0.2797, -1.7906,
          0.0361,  0.2365,  0.7417,  0.4630,  1.2603, -0.2132, -1.4090,  0.3888,
         -0.3893,  1.7778, -0.7607, -0.9531,  0.3680, -0.1011,  1.2089, -1.3241,
          0.8592,  1.3613,  0.0047,  1.1335,  0.2735, -0.4360, -0.8280, -0.8609,
          0.6738, -0.7555, -2.0181,  0.2973,  1.2908, -0.7536, -0.1255, -0.3316,
          0.3812,  2.2813, -0.4185, -1.8637, -0.9337,  0.1816,  1.2150, -0.1040,
         -0.8885, -1.7918,  0.6397,  0.8819, -1.1939,  1.4873,  0.0916,  1.5181,
          0.9647, -0.2276,  0.8804, -0.3842,  0.5960,  1.0743,  1.0564,  1.0861,
         -1.1323,  1.1305,  0.1348, -1.3628, -0.6954, -0.8944,  2.1736, -1.2461,
          0.1238, -1.3012, -0.7612,  0.6359, -0.8430,  1.6085, -0.7815, -0.2765,
          0.9462, -1.2970, -0.6932, -0.6934,  0.0837, -1.2487, -0.2776,  0.1983,
          0.1321, -1.6778,  0.8440,  0.1504,  0.1444,  0.6357,  0.2031,  1.4933,
          1.2094,  0.8259,  0.7184, -0.8211, -0.3794, -0.3777, -1.2583, -0.3226,
         -0.2352, -0.2312,  0.7106, -0.5659,  0.6313, -0.1088,  1.6111,  1.9486]],
       dtype=torch.float64), nan)

alt.Chart(...)